---
- name: Download the terraform zip archive.
  get_url:
    url: "{{ terraform_download_url }}"
    dest: /tmp
    checksum: sha256:{{ terraform_checksum_url }}
    mode: 0755
  register: terraform_download

- name: Unarchive the terraform archive.
  unarchive:
    src: "{{ terraform_download.dest }}"
    dest: /tmp
    mode: 0755
    remote_src: true

- name: Copy the terraform binary into place.
  copy:
    src: /tmp/terraform
    dest: "{{ terraform_bin_path }}"
    mode: 0755
    remote_src: true
  become: true
